sylius_ui:
    events:
        sylius.admin.login.form.content:
            blocks:
                alerts: '@SynoliaSyliusAdminOauthPlugin/alerts.html.twig'
                google_oauth_button: '@SynoliaSyliusAdminOauthPlugin/google_auth_button.html.twig'
                microsoft_oauth_button: '@SynoliaSyliusAdminOauthPlugin/microsoft_auth_button.html.twig'
        sylius.admin.layout.stylesheets:
            blocks:
                stylesoauth:
                    template: "@SynoliaSyliusAdminOauthPlugin/_styles.html.twig"
                    enabled: true