sylius_ui:
    events:
        sylius.admin.login.form.content:
            blocks:
                google_oauth_button: '@SynoliaSyliusAdminOauthPlugin/google_auth_button.html.twig'
                microsoft_oauth_button: '@SynoliaSyliusAdminOauthPlugin/microsoft_auth_button.html.twig'

twig:
    globals:
        google_client_id: '%env(default::OAUTH_GOOGLE_CLIENT_ID)%'
        microsoft_client_id: '%env(default::OAUTH_MICROSOFT_CLIENT_ID)%'
        
knpu_oauth2_client:
    clients:
        google_main:
            type: google
            client_id: '%env(default::OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(default::OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: 'connect_google_check'
            redirect_params: {}
        azure_main:
            type: azure
            client_id: '%env(default::OAUTH_MICROSOFT_CLIENT_ID)%'
            client_secret: '%env(default::OAUTH_MICROSOFT_CLIENT_SECRET)%'
            redirect_route: 'connect_microsoft_check'
            redirect_params: {}

#TODO: a faire dans le plugin
sylius_resource:
    resources:
        app.authorized_domain:
            classes:
                model: Synolia\SyliusAdminOauthPlugin\Entity\Domain\AuthorizedDomain
                repository: Synolia\SyliusAdminOauthPlugin\Repository\AuthorizedDomainRepository
                form: Synolia\SyliusAdminOauthPlugin\Form\Type\AuthorizedDomainType

winzou_state_machine:
    app_authorized_domain:
        class: "%app.model.authorized_domain.class%"
        property_path: isEnabled
        graph: app_authorized_domain
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            enabled: ~
        transitions:
            enable:
                from: [new]
                to: enabled
sylius_grid:
    grids:
        app_admin_authorized_domain:
            driver:
                options:
                    class: Synolia\SyliusAdminOauthPlugin\Entity\Domain\AuthorizedDomain
            sorting:
                name: asc
                isEnabled: asc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                isEnabled:
                    type: twig
                    label: sylius.ui.isEnabled
                    options:
                        template: "@SyliusUi/Grid/Field/state.html.twig"
                        vars:
                            labels: "AuthorizedDomain/Label/Status"
                    sortable: ~
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    enable:
                        type: apply_transition
                        label: sylius.ui.enable
                        icon: star
                        options:
                            link:
                                route: app_admin_authorized_domain_trust
                                parameters:
                                    id: resource.id
                            transition: enable
                            graph: app_authorized_domain
                            class: yellow
                bulk:
                    delete:
                        type: delete
            filters:
                name:
                    type: string
