sylius_twig_hooks:
    hooks:
        sylius_admin.security.login.page.content:
            template: 
                template: '@SynoliaSyliusAdminOauthPlugin/login_template.html.twig'
twig:
    globals:
        google_client_id: '%env(default::SYNOLIA_ADMIN_OAUTH_GOOGLE_CLIENT_ID)%'
        microsoft_client_id: '%env(default::SYNOLIA_ADMIN_OAUTH_MICROSOFT_CLIENT_ID)%'
        
knpu_oauth2_client:
    clients:
        google_admin:
            type: google
            client_id: '%env(default::SYNOLIA_ADMIN_OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(default::SYNOLIA_ADMIN_OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: 'connect_admin_google_check'
            redirect_params: {}
        azure_admin:
            type: azure
            client_id: '%env(default::SYNOLIA_ADMIN_OAUTH_MICROSOFT_CLIENT_ID)%'
            client_secret: '%env(default::SYNOLIA_ADMIN_OAUTH_MICROSOFT_CLIENT_SECRET)%'
            redirect_route: 'connect_admin_microsoft_check'
            redirect_params: {}

#TODO: a faire dans le plugin
sylius_resource:
    resources:
        app.authorized_domain:
            classes:
                model: Synolia\SyliusAdminOauthPlugin\Entity\Domain\AuthorizedDomain
                repository: Synolia\SyliusAdminOauthPlugin\Repository\AuthorizedDomainRepository
                form: Synolia\SyliusAdminOauthPlugin\Form\Type\AuthorizedDomainType

framework:
    workflows:
        app_authorized_domain:
            supports: 'Synolia\SyliusAdminOauthPlugin\Entity\Domain\AuthorizedDomain'
            transitions:
                isEnabled:
                    from: [new]
                    to: enabled

sylius_grid:
    grids:
        app_admin_authorized_domain:
            driver:
                options:
                    class: Synolia\SyliusAdminOauthPlugin\Entity\Domain\AuthorizedDomain
            sorting:
                name: asc
                isEnabled: asc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                isEnabled:
                    type: twig
                    label: sylius.ui.is_enabled
                    options:
                        template: "@SynoliaSyliusAdminOauthPlugin/state.html.twig"
                        vars:
                            labels: "AuthorizedDomain/Label/Status"
                    sortable: ~
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    enable:
                        type: apply_transition
                        label: sylius.ui.enable
                        icon: star
                        options:
                            link:
                                route: app_admin_authorized_domain_trust
                                parameters:
                                    id: resource.id
                            transition: enable
                            graph: app_authorized_domain
                            class: yellow
                bulk:
                    delete:
                        type: delete
            filters:
                name:
                    type: string
