connect_google:
    path: /connect/google
    defaults:
        _controller: Synolia\SyliusAdminOauthPlugin\Controller\GoogleController::switchAction

connect_google_check:
    path: /connect/google/check
    defaults:
        _controller: Synolia\SyliusAdminOauthPlugin\Controller\GoogleController::connectCheckAction
