controllers:
    resource:
        path: ../src/Controller/
        namespace: Synolia\SyliusAdminOauthPlugin\Controller
    type: attribute
    
app_admin_authorized_domain:
    resource: |
        alias: app.authorized_domain
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: app_admin_authorized_domain
        vars:
            all:
                subheader: app.ui.authorized_domains_subheader
            index:
                icon: 'file image outline'
    type: sylius.resource
