controllers:
    resource:
        path: ../src/Controller/
        namespace: Synolia\SyliusAdminOauthPlugin\Controller
    type: attribute
    
synolia_admin_oauth_authorized_domain:
    resource: |
        alias: synolia_admin_oauth.authorized_domain
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: synolia_admin_oauth_authorized_domain
        vars:
            all:
                header: synolia.sylius_admin_oauth.ui.authorized_domains.title
                subheader: synolia.sylius_admin_oauth.ui.authorized_domains.subheader
                breadcrumb: synolia.sylius_admin_oauth.ui.authorized_domains.menu_label
            index:
                icon: 'file image outline'
    type: sylius.resource
