connect_google:
    path: connect/google
    defaults:
        _controller: Synolia\SyliusAdminOauthPlugin\Controller\GoogleController::connectAction

connect_google_check:
    path: connect/google/check
    defaults:
        _controller: Synolia\SyliusAdminOauthPlugin\Controller\GoogleController::connectCheckAction
