# app/Resources/SyliusCoreBundle/config/app/state_machine/sylius_order_checkout.yml
winzou_state_machine:
    app_authorized_domain:
        class: "%app.model.authorized_domain.class%"
        property_path: isEnabled
        graph: app_authorized_domain
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            enabled: ~
        transitions:
            enable:
                from: [new]
                to: enabled
